### ISSUE TITLE
How to configure this to work on Compute Engine or App Engine

### ISSUE THREAD

**Issue by softpreneur** [axelspringer/graphql-google-pubsub#1]
Hi, Great work here. How can i configure this to work with Google compute engine or App Engine, All my graphql mutations, queries and subscriptions are working perfectly offline (localhost:3000), after pushing it to App engine, and later to compute engine everything works fine except subscriptions. How do i setup google compute engine to for graphql subscriptions to work? Step by step guide will be appreciated for setting up compute engine (Allow graphql subscriptions work)

**Comment by jonas-app** [comment]
Hey @motionboy,
this project should work also on Compute/App Engine.
Unfortunately I can't help you with the GraphQL setup as I don't use Compute/App Engine.
Good luck.
