### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by bsbechtel** [axelspringer/graphql-google-pubsub#17]
I'm seeing the following error when I try to use with netlify functions and apollo-server: 

```Error during invocation:  Error: package.json does not exist at /package.json```

Here are my dependencies:

```
  "devDependencies": {
    "netlify-lambda": "^1.5.1"
  },
  "dependencies": {
    "@axelspringer/graphql-google-pubsub": "^1.2.1",
    "apollo-server-lambda": "^2.8.1",
    "aws-sdk": "^2.343.0",
    "dotenv": "^6.1.0",
    "graphql": "^14.4.2",
    "mongoose": "^5.4.18",
    "uuid": "^3.2.1"
  }
```

I think it has something to do with netlify's webpack configuration, but it only started when I installed this package.

**Comment by jonas-app** [comment]
Thx for reporting this issue.

I have never used Netlify myself, so I'm afraid I ain't much help here.

Open for a contribution which fixes the issue if you find a solution.

**Comment by bsbechtel** [comment]
Thx....I ended up going another route. Google Pubsub was recommended to me by someone else.
