### ISSUE TITLE
Update package dependency for @google-cloud/pubsub to 0.20.0

### ISSUE THREAD

**Issue by stevesuh** [axelspringer/graphql-google-pubsub#7]
Looks like there are some bug fixes and also we use pubsub already so it would be nice to keep graphql-pubsub in sync.

https://github.com/googleapis/nodejs-pubsub/releases/tag/v0.20.0

**Comment by jonas-app** [comment]
@stevesuh Will do so as soon as I find some time.
Thanks for the report.
